# Homebrew tools, apps, and fonts recorded on 2026-09-14,
# plus dependencies required by the included app configurations.
# Review before installing; software versions follow Homebrew availability.
# Background services are not automatically enabled by this file.

tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"
tap "nikitabobko/tap"
brew "atuin"
brew "bat"
brew "btop"
brew "cmatrix"
brew "direnv"
brew "exercism"
brew "eza"
brew "fastfetch"
brew "fd"
brew "flyctl"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "go"
brew "htop"
brew "jq"
brew "just"
brew "lazygit"
brew "libomp"
brew "tree-sitter"
brew "neovim"
brew "newsboat"
brew "nmap"
brew "node"
brew "pandoc"
brew "prettier"
brew "powerlevel10k"
brew "python@3.12"
brew "python@3.13"
brew "ripgrep"
brew "ruff"
brew "starship"
brew "stylua"
brew "tldr"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
brew "typst"
brew "uv"
brew "wallpaper"
brew "wimlib"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# Required by the included SketchyBar configuration and AeroSpace integration.
brew "felixkratz/formulae/sketchybar"
cask "aerial"
cask "aerospace"
cask "alt-tab"
cask "docker-desktop"
cask "font-eb-garamond"
cask "font-geist-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-sf-pro"
cask "ghostty"
cask "hiddenbar"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "macwhisper"
cask "ubersicht"
cask "xscreensaver"
